# fly.toml app configuration file generated for bigdot-webserver on 2023-10-27T22:52:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bigdot-webserver"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
